ShareMockups/Areas/SinglePageApps/Controllers/HomeController.cs
using ShareMockups.DomainClasses;
using System.Web.Mvc;

namespace SinglePageApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            TrainingProductViewModel vm = new TrainingProductViewModel();

            vm.Get();

            return View(vm);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ShareMockups/Areas/SinglePageApps/Controllers/ShareMockupsController.cs
using ShareMockups.DomainClasses;
using System.Collections.Generic;
using System.Web.Mvc;

//namespace SinglePageApplication.Controllers
namespace ShareMockups.Controllers
{
    public class ShareMockupsController : Controller
    {
        public ActionResult Index()
        {
            //            TrainingProductManager mgr = new TrainingProductManager();  // to reduce code in the controller, we'll use the MVVM pattern by using TrainingProductViewModel instead.
            TrainingProductViewModel vm = new TrainingProductViewModel();

            // vm.Get(); // call the Get method on that view model to populate the Products collection
            // After implementing HandleRequest
            vm.HandleRequest();

            ViewData["Title"] = "ShareMockups Controller";

            //            return View(mgr.Get());
            return View(vm);  // passing the whole view model, because we're going to pass additional properties that the view can use.
        }

        [HttpPost]
        public ActionResult Index(TrainingProductViewModel vm)
        {
            vm.IsValid = ModelState.IsValid;  // MVC will validate the State and give it to ViewModel
            vm.HandleRequest();

            if (vm.IsValid)
            {
                ModelState.Clear();
            }
            else
            {
                foreach (KeyValuePair<string, string> item in vm.ValidationErrors)
                {
                    ModelState.AddModelError(item.Key, item.Value);
                }
            }

            return View(vm);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ShareMockups/Controllers/HomeController.cs
using ShareMockups.DataContexts;
using ShareMockups.DomainClasses;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace ShareMockups.Controllers
{
    public class HomeController : Controller
    {
        private static ShareMockupsContext ctx = new ShareMockupsContext();

        public ActionResult Index()
        {
            ShareMockupsViewModel vm = new ShareMockupsViewModel();

            vm.HandleRequest();

            ViewData["Foo"] = "Home Page";  //  Allows you to store data in a controller action that will be used in the corresponding view. 
                                            //  This assumes that the action returns a view and doesn't redirect. Lives only during the current request.

            return View(vm);     //.Mockups.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "This Page will be available soon.";

            return View();
        }

        public ActionResult Services()
        {
            ViewBag.Message = "This Page is Still Under Construction.";

            return View();
        }

        //[Authorize]
        public ActionResult IndexMockup()
        {

            return View(ctx.ShareMockups.ToList());

        }

        public ActionResult Create()
        {
            return View();
        }

        //POST: /Home/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize]
        public ActionResult Create([Bind(Include= "ShareMockupId,MockupName,Url,Description,Rate,Available")] ShareMockup sharemockup)
        {
            if (ModelState.IsValid)
            {
                ctx.ShareMockups.Add(sharemockup);
                ctx.SaveChanges();
                return RedirectToAction("IndexMockup");
            }

            return View(sharemockup);
        }

        //[Authorize]
        //GET: /Home/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ShareMockup sharemockup = ctx.ShareMockups.Find(id);

            if (sharemockup == null)
            {
                return HttpNotFound();
            }

            return View(sharemockup);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind(Include = "ShareMockupId,MockupName,Url,Description,Rate,Available")] ShareMockup sharemockup)
        {
           var model = ctx.ShareMockups.Single(s => s.ShareMockupId == id);

            if (TryUpdateModel(model))
            {
                ctx.Database.Log = sql => Debug.Write(sql);

                var attachedEntry = ctx.Entry(model);
                attachedEntry.CurrentValues.SetValues(model);

                ctx.SaveChanges();
                return RedirectToAction("IndexMockup");
            }
            return View(sharemockup);

        }

        //GET: /Home/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ShareMockup sharemockup = ctx.ShareMockups.Find(id);
            if (sharemockup == null)
            {
                return HttpNotFound();
            }

            return View(sharemockup);

        }

        //GET: /Home/Delete/5
        public ActionResult ShareMockupsDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ShareMockup sharemockup = ctx.ShareMockups.Find(id);
            if (sharemockup == null)
            {
                return HttpNotFound();
            }
            return View(sharemockup);

        }

        //POST: ShareMockups/Confirm Delete
        [HttpPost, ActionName("ShareMockupsDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult ShareMockupsDeleteConfirm(int? id)
        {
            ctx.Database.Log = sql => Debug.Write(sql);

            ShareMockup sharemockup = ctx.ShareMockups.Find(id);
            ctx.ShareMockups.Remove(sharemockup);
            ctx.SaveChanges();
            return RedirectToAction("IndexMockup");
        }

    }
}

ShareMockups/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ShareMockups/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ShareMockups/Views/Home/Create.cshtml
@model ShareMockups.DomainClasses.ShareMockup

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add a Mockup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MockupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MockupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MockupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Available)
                    @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserDefined, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserDefined, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserDefined, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserDefined2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.UserDefined2)
                    @Html.ValidationMessageFor(model => model.UserDefined2, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserDefined3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserDefined3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserDefined3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShareMockups/Views/Home/CreateMockup.cshtml
@model ShareMockups.DomainClasses.ShareMockup

@{
    ViewBag.Title = "CreateMockup";
}

<h2>CreateMockup</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ShareMockup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.MockupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MockupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MockupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Available)
                    @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserDefined, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserDefined, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserDefined, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserDefined2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.UserDefined2)
                    @Html.ValidationMessageFor(model => model.UserDefined2, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserDefined3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserDefined3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserDefined3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShareMockups/Views/Home/Details.cshtml
@model ShareMockups.DomainClasses.ShareMockup

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Details of Mockup Template</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MockupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MockupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ShareMockupId }) |
    @Html.ActionLink("Back to List", "IndexMockup")
</p>

ShareMockups/Views/Home/Edit.cshtml
@model ShareMockups.DomainClasses.ShareMockup

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit a Mockup Template</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShareMockupId)

        <div class="form-group">
            @Html.LabelFor(model => model.MockupName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MockupName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MockupName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Available)
                    @Html.ValidationMessageFor(model => model.Available, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexMockup")
</div>

ShareMockups/Views/Home/Index.cshtml
@model ShareMockups.DataContexts.ShareMockupsViewModel

@{
    ViewBag.Title = "Home Page";
}

@ViewBag.Foo

<div class="jumbotron">
    <h1>Mockups Templates</h1>
    <p class="lead">Mockups templates allow you to share your proof of concepts for software development purposes. Brainstorming ideas, UI design patterns, UX based on models, Code Reviews, and demos.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

@using (Html.BeginForm())
{
    <!-- BEGING HIDDEN FIELD AREA PROPERTYCHANGED EVENTS-->
    @Html.HiddenFor(m => m.EventCommand)
    @Html.HiddenFor(m => m.Mode)
    @Html.HiddenFor(m => m.EventArgument)
    <!-- END HIDDEN FIELDS AREA these fields are bound to the view model-->

    <!-- BEGIN List AREA-->
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-condensed table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Mockup Name</th>
                            <th>GitHub URL</th>
                            <th>Description</th>
                            <th>Rate</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Mockups)
                {
                            <tr>
                                <td>@Html.ActionLink(@item.MockupName, "Index", "ShareMockups")</td>
                                <td class="pdsa-action-button-column">
                                    <a href="@item.Url" data-mockup-action="run"
                                       data-mockup-val="@item.ShareMockupId">
                                    @item.Url</a>
                                </td>
                                <td>@item.Description</td>
                                <td>@item.Rate</td>
                            </tr>
                 }
                    </tbody>
                </table>
            </div>
            <!-- END OF LIST AREA-->
        </div>
    </div>
}

@*<div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                Share Mockups is an ASP.NET MVC application using terms and various approaches from agile development
                that enables the data gathering process a much easier practical tool as part of the Software Development
                Life Cycle.
            </p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Practical Tools - Mockups</h2>
            <p>Be sure your prototypes and/or wireframe are solid and have received sufficient customer feedback and validation.</p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Practical Tools - Business Rules</h2>
            <p>Capture all business rules in a single doc file.</p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@

ShareMockups/Views/Home/IndexMockup.cshtml
@model IEnumerable<ShareMockups.DomainClasses.ShareMockup>

@{
    ViewBag.Title = "Mockups Templates";
}

<h2>Mockups to demo</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MockupName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Available)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.UserDefined)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserDefined2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserDefined3)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MockupName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Available)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.UserDefined)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserDefined2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserDefined3)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ShareMockupId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ShareMockupId }) |
            @Html.ActionLink("Delete", "ShareMockupsDelete", new { id=item.ShareMockupId })
        </td>
    </tr>
}

</table>

ShareMockups/Views/Home/Services.cshtml
@{
    ViewBag.Title = "Services";
}

<p>Services available on a contract basis.</p>

<address>
    100 East Commercail Blvd<br />
    Fort Lauderdale, FL 33334<br />
    <abbr title="Phone">P:</abbr>
    954.225.9911
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ShareMockups/Views/Home/ShareMockupsDelete.cshtml
@model ShareMockups.DomainClasses.ShareMockup

@{
    ViewBag.Title = "Delete";
}

<h2>ShareMockupsDelete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShareMockup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MockupName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MockupName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Available)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "IndexMockup")
        </div>
    }
</div>